- name: Include network adapter detection tasks
  ansible.builtin.import_tasks: network_adapters.yml

- name: Include VMware Tools installation tasks
  ansible.builtin.import_tasks: vmware_tools.yml

- name: Include networking configuration tasks
  ansible.builtin.import_tasks: networking.yml

- name: Include PowerShell module tasks
  ansible.builtin.import_tasks: powershell_modules.yml

- name: Include Remote Desktop configuration tasks
  ansible.builtin.import_tasks: remote_desktop.yml

- name: Include licensing tasks
  ansible.builtin.import_tasks: licensing.yml
