---
# Remote Desktop configuration tasks
- name: Windows | Enable Remote Desktop
  community.windows.win_dsc:
    resource_name: RemoteDesktopAdmin
    IsSingleInstance: true
    Ensure: present
    UserAuthentication: Secure

- name: Firewall | Allow RDP through Firewall
  community.windows.win_dsc:
    resource_name: xFirewall
    Name: "Administrator access for RDP (TCP-In)"
    Ensure: present
    Enabled: true
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "3389"
    Protocol: "TCP"
    Description: "Opens the listener port for RDP"
