---
- name: "Read data files"
  hosts: domain:extensions
  connection: local
  vars_files:
    - "{{data_path}}/config.json"
  tasks:
    - name: Save the Json data to a variable as a fact
      ansible.builtin.set_fact:
        lab: "{{ lab }}"
        cacheable: true
